version: '3.5'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"

  fizzbuzz:
    build:
      context: ./
    environment:
      SERVER_PORT: 8080
      BD_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports:
      - "8083:8080"
    depends_on:
      - postgres
